my_string = input("Введите любое слово: ")
print("Количество введенных знаков - ", len(my_string), " символов")
print("В верхнем регистре: ", my_string.upper())
print("В нижнем регистре: ", my_string.lower())
print("Удаление пробелов ", my_string.strip(), "\nНовая длина - ", len(my_string.strip()), " знаков")
print("Первый введенный знак: ", my_string.strip()[0])
print("Последний знак слова: ", my_string.strip()[-1])
